<html>
<head>
<title>Some Form Stuff</title>
</head>
<link href="/sumthing.css" rel="stylesheet">
<body>
<div class="center card">
<form method="POST" action="sendposts.php" id="form">
<input type="text" class="center" name="postitle" placeholder="posttitle" /> <br>
<input type="Text" class="center" placeholder="Author" name="postauthor" /> <br>
<textarea class="center" id="postdata" name="postdata" rows="4" cols="50" form="form">
Write stuff here(html tags are allowed so you can add images videos etc.)
</textarea><br>
<input type="password" name="password" placeholder="Password"><br>
<input type="submit" name="submitted" value="SUBMIT">
</form>
</div>
</body>
</html>